import 'dart:convert';

class Autogenerated {
  PhoneIP d;

  Autogenerated({this.d});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    d = json['d'] != null ? new PhoneIP.fromJson(json['d']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.d != null) {
      data['d'] = this.d.toJson();
    }
    return data;
  }
}

class PhoneIP {
  String sType;
  String operator_;
  String iP;

  PhoneIP({this.sType, this.operator_, this.iP});

  PhoneIP.fromJson(String str) {
    Map<String, dynamic> jsonA = json.decode(str)["d"];
    sType = jsonA['__type'];
    operator_ = jsonA['Operator'];
    iP = jsonA['IP'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['__type'] = this.sType;
    data['Operator'] = this.operator_;
    data['IP'] = this.iP;
    return data;
  }
}
